# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build Package, Run unit tests & prepare coverage report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Package
      run: swift build -v

    - name: Run tests
      run: swift test --parallel --enable-code-coverage -v
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1.4.0
      with:
        xcode-version: "15.1"

    - name: Gather code coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/SwinjectorPackageTests.xctest/Contents/MacOS/SwinjectorPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage_report.lcov
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
            
